title: 果站
email: landg1220@163.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: LanDinGuo # add your name
author-pic: adam-face.jpg
about-author: Do Better,Do Yourself.

# Contact links
email: landg1220@163.com# Add your Email address
phone: 000000# Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: LanDingGuo # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

